services:
  - type: web
    name: jmalerba-portfolio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      # Window Seat is hosted on Azure and served under this path.
      - type: rewrite
        source: /projects/windowseat
        destination: https://icy-mud-0e682ef1e.1.azurestaticapps.net/projects/windowseat/
      - type: rewrite
        source: /projects/windowseat/*
        destination: https://icy-mud-0e682ef1e.1.azurestaticapps.net/projects/windowseat/*
      - type: rewrite
        source: /*
        destination: /index.html
